### ISSUE TITLE
Launch tasks

### ISSUE THREAD

**Issue by kript** [kript/unofficial_irods_documentation#1]
- [x] deploy to github pages [the instructions](https://www.mkdocs.org/user-guide/deploying-your-docs/)
- [x] add a theme
- [x] 'borrow' test and deploy tasks from https://github.com/bihealth/bih-cluster/tree/master/.github/workflows
- [x] add a [favicon](https://www.mkdocs.org/getting-started/#changing-the-favicon-icon)

**Comment by messersc** [comment]
Hi John,

thanks for setting this up. Let me know if I can help with anything here.

Clemens

**Comment by kript** [comment]
> Hi John,
> 
> thanks for setting this up. Let me know if I can help with anything here.
> 
> Clemens

Thanks! I'll try and spend some time making a first stab at them, and then I'll likely reach out.

**Comment by kript** [comment]
Wow, that's easy to deploy! https://kript.github.io/unofficial_irods_documentation/

**Comment by kript** [comment]
@messersc would you sort out a favicon, please?

**Comment by messersc** [comment]
What don't you like about the current one? Do you have a more fitting one in mind?

**Comment by kript** [comment]
I was thinking of something less generic/more iRODS  themed.

**Comment by messersc** [comment]
Either just:

![image](https://user-images.githubusercontent.com/9218116/179556068-f683b8cf-4fc5-4cc3-9d16-d8dec0502e2e.png)

or we can also have the R part blinking ;)

![image](https://user-images.githubusercontent.com/9218116/179556108-40d229ff-5e4c-4075-a689-f7a1995e73d1.png)
![image](https://user-images.githubusercontent.com/9218116/179556068-f683b8cf-4fc5-4cc3-9d16-d8dec0502e2e.png)

**Comment by kript** [comment]
I've been using `mkdocs gh-deploy` to push the changes to GitHub Pages, but I now realise that's a manual task. BIH has an [auto-deploy hook](https://github.com/bihealth/bih-cluster/blob/master/.github/workflows/mkdocs-deploy.yml) which I think can primarily be used here, but I think it needs a deploy token... More research is required from my side!

**Comment by kript** [comment]
> I've been using `mkdocs gh-deploy` to push the changes to GitHub Pages, but I now realise that's a manual task. BIH has an [auto-deploy hook](https://github.com/bihealth/bih-cluster/blob/master/.github/workflows/mkdocs-deploy.yml) which I think can primarily be used here, but I think it needs a deploy token... More research is required from my side!

Setup auto deploy! Net commit will be the tests.
