### ISSUE TITLE
pages not linking correctly

### ISSUE THREAD

**Issue by kript** [kript/unofficial_irods_documentation#2]
I've just added an about page, and while it generates the site OK, navigating to it, at least in the local `site/` rendering, doesn't work. 

Can anyone with more experience deploying MKDocs tell me what I've done wrong?

**Comment by messersc** [comment]
Hi John,

not sure what the problem is, navigation works fine for me when I serve the site locally with

```
mkdocs serve -a 127.0.0.1:8000
```

Can you describe a bit more how you generated the site?

**Comment by kript** [comment]
ah, that explains it- I just ran `mkdocs build` and pointed my browser at the index file. Thanks!
